name: Build LaTeX Documents
env:
  CONTAINER: blang/latex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker pull $CONTAINER

      - name: Build LaTeX Documents
        run: |
          docker run --name build-container -d -v ${{ github.workspace }}:/workspace $CONTAINER

    - name: Build
      env:
        SCRIPT: |
          cd workspace/template-rapport
          mkdir -p build/src
          latexmk -cd -outdir=./build -auxdir=./build -interaction=batchmode -pdf ./template-rapport.tex
      run: docker exec build-container bash -c "$SCRIPT"

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: template-rapport/build/*.pdf

