name: Build LaTeX Documents
env:
  CONTAINER: blang/latex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: |
          docker pull $CONTAINER

      - name: Start Docker Container
        run: |
          echo ${{ github.workspace }}
          docker run --name build-container -d -v ${{ github.workspace }}:/data $CONTAINER tail -f /dev/null

      - name: Build LaTeX Documents
        env:
          SCRIPT: |
            pwd && ls -la
            cd template-rapport
            mkdir -p build/src
            latexmk -cd -outdir=./build -auxdir=./build -interaction=batchmode -pdf ./template-rapport.tex
        run: docker exec build-container bash -c "$SCRIPT"

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: '**/*.pdf'

