name: Build LaTeX Documents
env:
  CONTAINER: blang/latex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker pull $CONTAINER

      - name: Build LaTeX Documents
        env:
          SCRIPT: |
            latexmk -cd -outdir=/data/template-rapport/build -auxdir=/data/template-rapport/build -interaction=batchmode -pdf /data/template-rapport/template-rapport.tex
        run: |
          docker run --rm -v ${{ github.workspace }}:/data $CONTAINER $SCRIPT

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: template-rapport/build/*.pdf

